"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, <CARSON MOORE>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: csm3682
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    '''This is the LinkedList class.'''
    def __init__(self):
        '''This is the initializer for the linked list class.'''
        self.head = None


    def insert_term(self, coeff, exp):
        ''' This code inserts the term with the coefficient coeff and 
        exponent exp into the polynomial.If a term with that exponent
        already exists, then it adds the coefficients together. You must keep
        the terms in descending order by exponent.'''
        if coeff == 0:
            return

        previous = None
        current = self.head
        new_node = Node(coeff, exp)


        while current and current.exp > exp:
            previous = current
            current = current.next

        if current and current.exp == exp:
            current.coeff += coeff
            if current.coeff == 0:
                if previous:
                    previous.next = current.next
                else:
                    self.head = current.next
            return
        if previous is None:
            self.head = new_node

        else:
            previous.next = new_node
        new_node.next = current




    def add(self, p):
        '''This function adds a polynomial p to the polynomial and return the resulting polynomial 
        as a new linked list.'''
        result = LinkedList()
        node_1 = self.head
        node_2 = p.head

        while node_1 or node_2:
            if node_1 and (not node_2 or node_1.exp > node_2.exp):
                result.insert_term(node_1.coeff, node_1.exp)
                node_1 = node_1.next
            elif node_2 and (not node_1 or node_2.exp > node_1.exp):
                result.insert_term(node_2.coeff, node_2.exp)
                node_2 = node_2.next
            else:
                sum_coefficients = node_1.coeff + node_2.coeff
                if sum_coefficients != 0:
                    result.insert_term(node_1.coeff + node_2.coeff, node_1.exp)
                node_1 = node_1.next
                node_2 = node_2.next
        return result


    def mult(self, p):
        '''Multiply a polynomial p with the polynomial and return the product as a new 
        linked list.'''
        product = LinkedList()
        node_1 = self.head

        while node_1:
            node_2 = p.head
            while node_2:
                product.insert_term(node_1.coeff * node_2.coeff, node_1.exp + node_2.exp)
                node_2 = node_2.next
            node_1 = node_1.next

        return product

    # Return a string representation of the polynomial.
    def __str__(self):
        if not self.head:
            return ""
        terms = []
        node = self.head
        while node:
            if node.coeff != 0:
                terms.append("(" + str(node.coeff) + ", " + str(node.exp) + ")")
            node = node.next
        return " + ".join(terms)


def main():
    ''' This function reads data from stdin using input() and creates polynomial p

    It reads data from stdin using input() and create polynomial q

    Then it gets the sum of p and q as a new linked list and print sum

    Finally it gets the product of p and q as a new linked list and prints the product'''
    p = LinkedList()
    n = int(input().strip())
    for _ in range(n):
        term = input().strip().split()
        coeff = int(term[0])
        exp = int(term[1])
        p.insert_term(coeff, exp)

    input()

    q = LinkedList()
    m = int(input().strip())
    for _ in range(m):
        term = input().strip().split()
        coeff = int(term[0])
        exp = int(term[1])
        q.insert_term(coeff, exp)

    sum_pq = p.add(q)
    print(sum_pq)

    product = p.mult(q)
    print(product)



if __name__ == "__main__":
    main()
